### ISSUE TITLE
How to integrate in pre-commit?

### ISSUE THREAD

**Issue by Yajo** [prettier/plugin-xml#17]
Hello, I mainly program in Python and XML, and I'd love to use prettier for the XML part, but I don't have any npm, yarn, package.json or JS thingies in my projects.

I use pre-commit. Is there a way to include prettier plugins in a `.pre-commit-config.yaml` file?

**Comment by Yajo** [comment]
I got it working with this, although I'd expect some native out-of-the-box support here (or in prettier itself):

```yaml
# .pre-commit-config.yaml
default_language_version:
  python: python3
repos:
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: c0573b2f7c5f39fddf1c5b8b4528cc73686df524
    hooks:
      - id: prettier
        name: prettier xml plugin
        additional_dependencies:
          - prettier@1.19.1
          - "@prettier/plugin-xml@0.3.0"
        files: \.xml$
        exclude: /static/lib/
```
