### ISSUE TITLE
pre-commit hook with xml plugin not working

### ISSUE THREAD

**Issue by Gaelik-git** [prettier/plugin-xml#673]
I am using this set up 

```yml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        additional_dependencies:
         - "@prettier/plugin-xml@2.2.0"
```

When using `pre-commit run -a` I get this error 
```
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

Executable `prettier` not found
```
The error disappear if I remove the plugin.
Is there a way to fix this without having to globally install prettier ?

**Comment by Gaelik-git** [comment]
I actually find the solution 

I did not follow the example from https://github.com/pre-commit/mirrors-prettier correctly

```yml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude: ^CHANGELOG.md|^README.md
        additional_dependencies:
          - "prettier@2.8.8"
          - "@prettier/plugin-xml@2.2.0"
```
